"""change constranis

Revision ID: 4ac82053d688
Revises: efbf29d45f40
Create Date: 2026-02-04 16:05:21.997339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac82053d688'
down_revision: Union[str, Sequence[str], None] = 'efbf29d45f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_product_items_price_positive', 'product')
    op.drop_constraint('ck_product_items_quantity_positive', 'product')
    op.create_check_constraint('ck_product_items_price_positive', 'product', 'price >= 0')
    op.create_check_constraint('ck_product_items_quantity_positive', 'product', 'quantity >= 0')
    op.drop_constraint('ck_orders_items_quantity_positive', 'ordersitems')
    op.drop_constraint('ck_orders_items_unit_price_positive', 'ordersitems')
    op.create_check_constraint('ck_orders_items_quantity_positive','ordersitems', 'quantity >= 0')
    op.create_check_constraint('ck_orders_items_unit_price_positive', 'ordersitems', 'unit_price >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_product_items_price_positive', 'product')
    op.drop_constraint('ck_product_items_quantity_positive', 'product')
    op.create_check_constraint('ck_product_items_price_positive', 'product', 'price > 0')
    op.create_check_constraint('ck_product_items_quantity_positive', 'product', 'quantity > 0')
    op.drop_constraint('ck_orders_items_quantity_positive', 'ordersitems')
    op.drop_constraint('ck_orders_items_unit_price_positive', 'ordersitems')
    op.create_check_constraint('ck_orders_items_quantity_positive','ordersitems', 'quantity > 0')
    op.create_check_constraint('ck_orders_items_unit_price_positive', 'ordersitems', 'unit_price > 0')
    # ### end Alembic commands ###
